gui:
  theme:
    selectedLineBgColor:
      - reverse
    selectedRangeBgColor:
      - reverse
os:
  edit: "nvim --server $NVIM --remote {{filename}}"
  editAtLine: "nvim --server $NVIM --remote {{filename}} && nvim --server $NVIM --remote-send ':{{line}}<CR>'"
git:
  pagers:
    - colorArg: always
      pager: delta --dark --paging=never --features=lazygit
