# Tab 栏样# 背景壁纸设置
background_image         /Users/shawn/Documents/Personal/Wallpaper/月光下的锈蚀灯塔与暖屋.png
background_image_layout  scaled
# Tint 设为 0.85，既能看清壁纸，又能保证代码文字清晰
background_tint          0.90
background_tint_gaps     -10.0

# 窗口透明度 (有壁纸时建议设为 1.0，否则背景会叠加桌面导致脏乱)
background_opacity       1.0
background_blur          0

# Tab 栏样式：Powerline 倾斜风格
tab_bar_edge            bottom
tab_bar_style           powerline
tab_powerline_style     slanted
tab_bar_min_tabs        1
tab_title_template      "{title}{' :{}:'.format(num_windows) if num_windows > 1 else ''}"

# 激活窗口边框高亮 (青色)
active_border_color     #44ffff
inactive_text_alpha     0.6
window_margin_width     10
window_border_width     1pt

# 光标样式 (Beam 形态，平滑闪烁)
cursor_shape            beam
cursor_beam_thickness   1.5
cursor_blink_interval   0.5
shell_integration       no-cursor1

cursor_trail 1
cursor_trail_decay 0.1 0.4
cursor_trail_start_threshold 2
