# 字体族名称
font_family      FiraCode Nerd Font Mono
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size        14.0

# 连字设置 (Ligatures)
disable_ligatures never

# 针对 macOS 的字体平滑优化
macos_thicken_font 0.1
