# 禁用 Shell 集成对光标形状的强制修改
shell_integration no-cursor

# 性能优化
scrollback_lines      10000
scrollback_pager      nvim -c 'set signcolumn=no' -
repaint_delay         10
input_delay           3
sync_to_monitor       yes

editor nvim

# 退出时不确认
confirm_os_window_close 0
