# 快速重新加载配置 (Cmd+Shift+R 或 Ctrl+Shift+R)
map ctrl+shift+r load_config_file

map cmd+shift+page_up move_tab_backward

#: Move tab backward
map cmd+shift+page_down move_tab_forward

# 在 kitty.conf 中添加：
map ctrl+shift+z toggle_layout stack

map cmd+1    goto_tab 1
map cmd+2    goto_tab 2
map cmd+3    goto_tab 3
map cmd+4    goto_tab 4
map cmd+5    goto_tab 5
map cmd+6    goto_tab 6

# 清屏（含滚回）
map cmd+k    combine : clear_terminal scrollback active : send_text normal,application \x0c


# 使用 Alt + 方向键 调整窗口大小
map alt+left  resize_window narrower 2
map alt+right resize_window wider 2
map alt+up    resize_window taller 2
map alt+down  resize_window shorter 2

map ctrl+shift+r load_config_file
