# ==========================================================
# Kitty 主配置文件
# ==========================================================

# 1. 引入模块化配置
include conf.d/fonts.conf
include conf.d/Bar&Window&Color.conf
include conf.d/keybindings.conf
include conf.d/general.conf

